/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ConsoleRouteImport } from './routes/console'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ConsoleWorkspaceRouteImport } from './routes/console/workspace'
import { Route as ConsoleWorkspaceSocialRouteImport } from './routes/console/workspace/social'
import { Route as ConsoleWorkspaceProfessionalRouteImport } from './routes/console/workspace/professional'

const ConsoleRoute = ConsoleRouteImport.update({
  id: '/console',
  path: '/console',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ConsoleWorkspaceRoute = ConsoleWorkspaceRouteImport.update({
  id: '/workspace',
  path: '/workspace',
  getParentRoute: () => ConsoleRoute,
} as any)
const ConsoleWorkspaceSocialRoute = ConsoleWorkspaceSocialRouteImport.update({
  id: '/social',
  path: '/social',
  getParentRoute: () => ConsoleWorkspaceRoute,
} as any)
const ConsoleWorkspaceProfessionalRoute =
  ConsoleWorkspaceProfessionalRouteImport.update({
    id: '/professional',
    path: '/professional',
    getParentRoute: () => ConsoleWorkspaceRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/console': typeof ConsoleRouteWithChildren
  '/console/workspace': typeof ConsoleWorkspaceRouteWithChildren
  '/console/workspace/professional': typeof ConsoleWorkspaceProfessionalRoute
  '/console/workspace/social': typeof ConsoleWorkspaceSocialRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/console': typeof ConsoleRouteWithChildren
  '/console/workspace': typeof ConsoleWorkspaceRouteWithChildren
  '/console/workspace/professional': typeof ConsoleWorkspaceProfessionalRoute
  '/console/workspace/social': typeof ConsoleWorkspaceSocialRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/console': typeof ConsoleRouteWithChildren
  '/console/workspace': typeof ConsoleWorkspaceRouteWithChildren
  '/console/workspace/professional': typeof ConsoleWorkspaceProfessionalRoute
  '/console/workspace/social': typeof ConsoleWorkspaceSocialRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/console'
    | '/console/workspace'
    | '/console/workspace/professional'
    | '/console/workspace/social'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/console'
    | '/console/workspace'
    | '/console/workspace/professional'
    | '/console/workspace/social'
  id:
    | '__root__'
    | '/'
    | '/console'
    | '/console/workspace'
    | '/console/workspace/professional'
    | '/console/workspace/social'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ConsoleRoute: typeof ConsoleRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/console': {
      id: '/console'
      path: '/console'
      fullPath: '/console'
      preLoaderRoute: typeof ConsoleRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/console/workspace': {
      id: '/console/workspace'
      path: '/workspace'
      fullPath: '/console/workspace'
      preLoaderRoute: typeof ConsoleWorkspaceRouteImport
      parentRoute: typeof ConsoleRoute
    }
    '/console/workspace/social': {
      id: '/console/workspace/social'
      path: '/social'
      fullPath: '/console/workspace/social'
      preLoaderRoute: typeof ConsoleWorkspaceSocialRouteImport
      parentRoute: typeof ConsoleWorkspaceRoute
    }
    '/console/workspace/professional': {
      id: '/console/workspace/professional'
      path: '/professional'
      fullPath: '/console/workspace/professional'
      preLoaderRoute: typeof ConsoleWorkspaceProfessionalRouteImport
      parentRoute: typeof ConsoleWorkspaceRoute
    }
  }
}

interface ConsoleWorkspaceRouteChildren {
  ConsoleWorkspaceProfessionalRoute: typeof ConsoleWorkspaceProfessionalRoute
  ConsoleWorkspaceSocialRoute: typeof ConsoleWorkspaceSocialRoute
}

const ConsoleWorkspaceRouteChildren: ConsoleWorkspaceRouteChildren = {
  ConsoleWorkspaceProfessionalRoute: ConsoleWorkspaceProfessionalRoute,
  ConsoleWorkspaceSocialRoute: ConsoleWorkspaceSocialRoute,
}

const ConsoleWorkspaceRouteWithChildren =
  ConsoleWorkspaceRoute._addFileChildren(ConsoleWorkspaceRouteChildren)

interface ConsoleRouteChildren {
  ConsoleWorkspaceRoute: typeof ConsoleWorkspaceRouteWithChildren
}

const ConsoleRouteChildren: ConsoleRouteChildren = {
  ConsoleWorkspaceRoute: ConsoleWorkspaceRouteWithChildren,
}

const ConsoleRouteWithChildren =
  ConsoleRoute._addFileChildren(ConsoleRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ConsoleRoute: ConsoleRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
